//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCustomer()
        {
            this.TblHistory = new HashSet<TblHistory>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerSurname { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<System.DateTime> CustomerBringDate { get; set; }
        public Nullable<System.DateTime> CustomerDeliveryDate { get; set; }
        public string CustomerRequest { get; set; }
        public Nullable<int> CustomerCarBrandId { get; set; }
        public Nullable<int> CustomerMechanicId { get; set; }
        public Nullable<int> CustomerAdminId { get; set; }
        public string CustomerCarPlateNumber { get; set; }
    
        public virtual TblAdmin TblAdmin { get; set; }
        public virtual TblBrand TblBrand { get; set; }
        public virtual TblMechanic TblMechanic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblHistory> TblHistory { get; set; }
    }
}
