//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHistory
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Info { get; set; }
    
        public virtual TblCustomer TblCustomer { get; set; }
    }
}
